### ISSUE TITLE
DiscogsDataset object has no attribute 'dataset_file'

### ISSUE THREAD

**Issue by saezbaldo** [palonso/MAEST#1]
While running the first config script:

python ex_maest.py

Exception ignored in: <function DiscogsDataset.__del__ at 0x7fcb56616680>
Traceback (most recent call last):
  File "/home/jack30time/MAEST/discogs/dataset.py", line 59, in __del__
    if self.dataset_file is not None:
AttributeError: 'DiscogsDataset' object has no attribute 'dataset_file'

**Comment by palonso** [comment]
Hi @saezbaldo, thank you for reporting this issue. 

The error you mention is due to an incorrect implementation of the `__del__` method in the `DiscogsDataset` that I will fix now.

However, I guess the actual problem is that your script is configured to use ground truth files that are not present (e.g., `discogs/gt_train_all_400l_super_clean.pk`). In this case, you should be getting something like this in your log (before the error you mentioned):

```
  File "/home/palonso/reps/MAEST/discogs/dataset.py", line 42, in __init__
    with open(groundtruth_file, "rb") as gf:
FileNotFoundError: [Errno 2] No such file or directory: 'discogs/gt_train_all_400l_super_clean.pk'
```

As explained in the doc, the ground truth files are not supplied in the repo because the training data is not public. [Here](https://github.com/palonso/MAEST#pre-training-data) we point out how to construct your training dataset with your custom data.
